---
abstract: 'Write Perl subs and classes in Python.'
author:
  - 'Neil Watkiss <NEILW@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Parse::RecDescent: '1.967013'
  Proc::ProcessTable: '0.53'
  Test: '0'
  Test::Deep: '0'
  Test::More: '0'
  Test::Number::Delta: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Inline-Python
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: '0'
  Digest::MD5: '2.5'
  Inline: '0.46'
resources:
  repository: http://github.com/niner/inline-python-pm.git
version: '0.56'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
